name: Publish to PyPI

on:
  push:
    tags:
      - "v*" # Trigger only on version tags (e.g., v1.0.0)

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Build the frontend into the package
      run: ./scripts/build_frontend.sh

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install build dependencies
      run: pip install build twine

    - name: Build the package
      run: python -m build

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
